{{- if .Values.alert.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-manager
  namespace: {{ include "tensor-fusion.namespace" . }}
  labels:
    tensor-fusion.ai/component: alert-manager
    {{- include "tensor-fusion.labels" . | nindent 4 }}
{{- end }}
